version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USER=root
    env_file:
      - "./.env"
    volumes:
      - ./mysql:/var/lib/mysql/

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/
    working_dir: /app/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - "./.env"
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api
