version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/
    working_dir: /app/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - "./.env"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api

